name: Run rspec, rubocop-rails

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose build --no-cache
        run: docker-compose build

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: sleep for waiting launch db
        run: sleep 1m

      - name: setup db
        run: docker-compose run --rm api rails db:create db:migrate

      - name: rspec
        run: docker-compose run --rm api rspec

      - name: rubocop
        run: docker-compose run --rm api rubocop

      - name: docker-compose down
        run: docker-compose down